# Site settings
title: bengkelFOTO.com - Digital Image Services
email: info.bengkelfoto@gmail.com
description: Image repair and manipulation.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://bengkelfoto.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
#data-ad-slot: 2973388149
#data-ad-client: ca-pub-9204963049240271
#google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-96478731-1"
addthis_id: ra-58dca52cfdbcafea
disqus_account: bengkelfoto

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/andikabetha
  - title: facebook
    url: https://facebook.com/andika.betha
  - title: google-plus
    url: https://plus.google.com/+AndikaBethaAdhikrisna
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
